version: 2.1
  orbs:
    aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - setup_remote_docker
      - run
          name: Prepare fcos.fcc for build script
          command: sed -i 's#<insert ssh key here>#${SSH_KEY}#g' fcos.fcc
      - run
          name: Run coreos build script
          command: source build-coreos.sh
      - aws-s3/sync
          from: coreos-build-single
          to: 's3://environments.chaseweyer.com'

workflows:
  build:
    jobs:
      - build:
          filters:
            only: master
